apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-nginx
  labels:
    app: my-release-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-release-nginx
  template:
    metadata:
      labels:
        app: my-release-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
